random_seed: 12345
addnum: 10
feedback_epochs: 10
dataset:
    is_created: False
    n_users: 500
    n_items: 1000
    rating_scale:
        - 1
        - 5
    epsilon: 0.5
    time_range: 40
mf:
    n_factors: 100
    lr: 0.00001
    reg: 1.5
    n_epochs: 5

algo:
    - "conventional_mf"
    - "ips_mf"
    - "random"
